### ISSUE TITLE
Is there an example of a ROS node running a grpc server ?

### ISSUE THREAD

**Issue by abishekh** [CogRob/catkin_grpc_examples#2]
I'm trying to use grpc with ROS and I'm running into issues with Async spinners. Could you provide an example of the grpc integration with ros code ?

**Comment by BillWSY** [comment]
We do have a lot of internal code relying on gRPC and ROS, but they are not yet polished to be released yet. We plan to release our Google Cloud Speech code in about a month, which uses async gRPC and async ROS spinner.

**Comment by BillWSY** [comment]
FYI, we just open-sourced gcloud_speech package.
See: https://github.com/CogRob/gcloud_speech
It uses ROS SimpleActionServer, and async grpc client.

**Comment by abishekh** [comment]
thanks!
