### ISSUE TITLE
Protobuf with multiple import dependencies

### ISSUE THREAD

**Issue by abishekh** [CogRob/catkin_grpc_examples#4]
Hi,
I'm trying this setup out to use protobufs through catkin on my ROS projects. In the CMakeLists.txt on line 21 : 
 `target_link_libraries(hello_proto hello_msg_proto)`
the target for hello_proto is specified to link against hello_msg_proto, but my use case has protobufs with multiple protos as dependencies. Do I need to specify a `generate_proto` for each ? and how would I handle inter-target cycles ?

Thanks

**Comment by BillWSY** [comment]
The only requirement is that your final target should depends on all of the proto targets, directly or indirectly. Your final target can either depend on both hello_msg_proto and hello_proto directly, or depend on hello_msg_proto via hello_proto indirectly (as shown in the example).

**Comment by BillWSY** [comment]
Also, one generate_proto can handle multiple proto files, so you can list all the proto files together.

**Comment by abishekh** [comment]
Thank-you!
